### PR TITLE
V1.5.0

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9#-NImE6ExBLW1hqqq5y2r:-NImE6Ey9WJS_M698MET:bbuzpf8) ([raw file](https://github.com/moka-guys/dnanexus_tso500/blob/6c5d682d9e7891fb59b795107036971a6e95051c/README.md#L12)):*
> ```Markdown
> * analysis_options -  a string which can be passed to the ruo command line
> 
> ## How does this app work?
> ```

can you add here how it gets the data in, using the project id

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9#-NImE6ExBLW1hqqq5y2r:-NImFxxq77N1LPGDSO5I:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_tso500/blob/6c5d682d9e7891fb59b795107036971a6e95051c/README.md#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you add here how it gets the data in, using the project id
</blockquote></details>

Done.

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9#-NImE6ExBLW1hqqq5y2r:-NImGiVZ6Rl5AEOxTm8c:bmuotkb) ([raw file](https://github.com/moka-guys/dnanexus_tso500/blob/6c5d682d9e7891fb59b795107036971a6e95051c/README.md#L12)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry to be fussy, in case anyone else uses this app, can you state here where exactly the data is downloaded from?

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9#-NImE6ExBLW1hqqq5y2r:-NImIPMt1rzVzBrKP9MX:bsgan97) ([raw file](https://github.com/moka-guys/dnanexus_tso500/blob/6c5d682d9e7891fb59b795107036971a6e95051c/README.md#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry to be fussy, in case anyone else uses this app, can you state here where exactly the data is downloaded from? 
</blockquote></details>

Sorry is this better?

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @natashapinto)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9#-NImE6ExBLW1hqqq5y2r:-NImJnIC8lprrJpZLkPU:b-ucfknh) ([raw file](https://github.com/moka-guys/dnanexus_tso500/blob/6c5d682d9e7891fb59b795107036971a6e95051c/README.md#L12)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Sorry is this better?
</blockquote></details>

Thanks!

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
